services:
  postgres:
    image: bitnami/postgresql
    container_name: movieflixcontainer
    environment:
      POSTGRES_DB: movieflix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    restart: always