spring:
  application:
    name: movieflix

  datasource:
    url: jdbc:postgresql://localhost:5434/movieflix
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    dbl-auto: none

  flyway:
    enabled: true
